#!/usr/bin/env python3

'''
Initial script written by William Paivine (bill@paivine.com).

Updated/Maintined by Rohan Yadav (rohany@alumni.cmu.edu)
'''

import sys
from diderot_core import DiderotCLI, DiderotCLIArgumentGenerator

if __name__ == '__main__':
    args = DiderotCLIArgumentGenerator.generate_args()
    if args.command != None:
        cli = DiderotCLI(args.url, args.username, args.password, shouldPrintLoginMessage=False)
        cli.initialize()
        cli.onecmd(args.command)
    else:
        DiderotCLI(args.url, args.username, args.password).cmdloop()
